# Generated by Django 4.2 on 2023-04-24 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("talent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("points", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("times_completed", models.PositiveIntegerField(default=1)),
                (
                    "talent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="talent.talent"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
